### ISSUE TITLE
Improve and update documentation / clean repository for deprecated files

### ISSUE THREAD

**Issue by nilodna** [lhico/pyroms_tools#32]
I'm taking a look in the current dev branch and found a few deprecated files (like [this](https://github.com/lhico/pyroms_tools/blob/dev/scripts/era2roms.py)). I believe we have to clean the house a little bit.

Also, we must improve the documentation (README) to add instructions regarding the xESMF usage: which scripts run outside docker? how to create a new environment for it?

I decided to create this issue to keep these notes on track and to remind us to do it.

--------------------

**To-do List:**

- [ ] create documentation on how to use the xESMF-related scripts, such as the initial condition file;
- [ ] update documentation on how to use docker to generate input files (when, how, and why perhaps);
- [x] clean deprecated files, such as ```era2roms.py```

**Comment by dksasaki** [comment]
yeah, this is imporant.

we really need to get rid of a few old scripts that really don't belong to pyroms_tools.

Let's create a to-do list.

**Comment by nilodna** [comment]
I'll create a to-do list on the original post of this issue.

**Comment by nilodna** [comment]
The code was cleaned in #39 by @dksasaki

**Comment by dksasaki** [comment]
I think we can close  this issue, since we are reworking the entire package?
